#!/bin/sh

###
### --- Definicao de Variaveis dependentes do ambiente ---
###

# Hostname do controlador SAGE2 
HOSTNAME=192.168.2.114

# Porta para acesso HTTPS (identificada como index no arquivo .json)
PORT=9090                     

# Diretorio com os arquivos do SAGE2
SAGE_DIR="/home/lassu/Desktop/sage2"

# Indice do ultimo monitor (valor igual a quantidade de monitores -1) 
LAST_MONITOR=0  

###
### -------- NAO MEXER DAQUI PARA BAIXO ----------------
###


# Parametros----------------------------------------------------------------------------
BASE_URL="https://$HOSTNAME:$PORT"
CHROME_PARAM="--window-size=800,600 --window-position=0,0 --args --new-window --disable-popup-blocking --no-first-run --use-gl --enable-accelerated-compositing --allow-file-access-from-files --disable-session-crashed-bubble --allow-running-insecure-content"
CHROME_SESSIONDIR="$HOME/.config/chrome/session"
CHROME_CMD="google-chrome $CHROME_PARAM"

# Funcoes------------------------------------------------------------------------------

xdotoolUnlock (){
  xdotool mousemove --screen $1 700 400
  xdotool click 1
  sleep 1
  xdotool mousemove --screen $1 700 570
  xdotool click 1
  sleep 1
} 

xdotoolFullscreen (){
  xdotool key F11
}

# Execução GO------------------------------------------------------------------------------

# para nao ocorrer problema na abertura do chrome
# é deletado as sessions criadas, com excecao do Default
# para nao perguntar sobre o navegador Default
#cd $CHROME_DIR

# acessa o diretorio do ./GO-server
cd $SAGE_DIR

# fecha qualquer processo do server que esteja ativo
killall -9 server.js
# fecha qualquer instacia do google-chrome para evitar conflito de sessoes
killall -9 chrome
# execucao do server
xterm -e "node server.js -l" &

sleep 4


for ID in `seq 0 $LAST_MONITOR`; do
  echo "-----------------------------"
  echo "-------- Session $ID --------"
  echo "-----------------------------"

  # para nao ocorrer problema na abertura do chrome
  # é deletado as sessions criadas, com excecao do Default
  # para nao perguntar sobre o navegador Default
  
  #  cd ${CHROME_SESSIONDIR}$ID
  #  rm -rf Default # recursivo force
  mkdir -p ${CHROME_SESSIONDIR}$ID
  
  export DISPLAY=:0.$ID
  #  env DISPLAY=:0.$ID
  #sleep 1

  if [ $ID -eq 0 ]; then

    #-------------------------------------------------
    # Audio Manager
    # abre pagina do audio manager (videos so funcionam com audio manager ativado)
    # 
    $CHROME_CMD --user-data-dir=${CHROME_SESSIONDIR}$ID --app=$BASE_URL/audioManager.html &
    sleep 7
  
    xdotoolUnlock $ID
  
  fi

  #-------------------------------------------------
  # Display Screen
  #
  $CHROME_CMD --user-data-dir=${CHROME_SESSIONDIR}$ID --app=$BASE_URL/display.html\?clientID=$ID &
  sleep 2

  #-------------------------------------------------
  # comandos com xdotool para fullscreen
  #
  # xdotoolUnlock $ID
  # xdotool key F11
  # xdotoolFullscreen 
  
done

# volta para screen 0
xdotool mousemove --screen 0 50 50
xdotool click 1
